on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-contracts-action:
    runs-on: ubuntu-latest
    name: test filecoin action
    steps:
      - id: localnet
        uses: hammertoe/filecoin-fvm-localnet@3a243be6915824bf1e4cddd30847a7a4ba8ad1d0
      - run: echo "Address:" ${{ steps.localnet.outputs.filAddress }}
